name: Run Tests on Push or PR

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main, 'feature/*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
